### ISSUE TITLE
Suggestion: Pedagogical Git Branching

### ISSUE THREAD

**Issue by punkstarman** [sebiwi/nginx#1]
When developing, the end state is the most important one. The intermediate states are there just in case.

When writing a tutorial, intermediate states are just as important. Plus the user probably wants to be able to go through the different steps from the beginning.

I suggest you add tags or branches that reference the various interesting commits, especially one that references the earliest commit where only the scaffolding of the project is present.

**Comment by sebiwi** [comment]
Sounds good. It's done.
